### ISSUE TITLE
Python 3.5 support?

### ISSUE THREAD

**Issue by hunt3r** [contentful-labs/contentful.py#16]
Seeing this error when installing for python3.5

```
Collecting enum34==1.0.4 (from contentful.py==0.9.2->-r requirements.txt (line 11))
  Downloading http://pypi.urbn.com/root/pypi/+f/984/3e97527f3126c/enum34-1.0.4.zip (43kB)
    100% |████████████████████████████████| 51kB 21.4MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/private/var/folders/s2/4d05wd7d7pj3tx8lp550ksc148jm0q/T/pip-build-7a75kk_d/enum34/enum/__init__.py", line 371, in __getattr__
        return cls._member_map_[name]
    KeyError: '_convert'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/hunterc1/projects/URBNLocal/source/URBNWeb/venv/lib/python3.5/site-packages/setuptools/__init__.py", line 11, in <module>
        from setuptools.extern.six.moves import filterfalse, map
      File "/Users/hunterc1/projects/URBNLocal/source/URBNWeb/venv/lib/python3.5/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/Users/hunterc1/projects/URBNLocal/source/URBNWeb/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 32, in <module>
        import platform
      File "/Users/hunterc1/.pyenv/versions/3.5.2/lib/python3.5/platform.py", line 117, in <module>
        import sys, os, re, subprocess
      File "/Users/hunterc1/.pyenv/versions/3.5.2/lib/python3.5/subprocess.py", line 364, in <module>
        import signal
      File "/Users/hunterc1/.pyenv/versions/3.5.2/lib/python3.5/signal.py", line 8, in <module>
        _IntEnum._convert(
      File "/private/var/folders/s2/4d05wd7d7pj3tx8lp550ksc148jm0q/T/pip-build-7a75kk_d/enum34/enum/__init__.py", line 373, in __getattr__
        raise AttributeError(name)
    AttributeError: _convert

```

Could enum34 be replaced with the core 3.5 package?

**Comment by hunt3r** [comment]
Found some info on the issue here:
https://bitbucket.org/stoneleaf/enum34/issues/5/enum34-incompatible-with-python-35

**Comment by hunt3r** [comment]
We're trying to move our tornado project into 3.5 to take advantage of the async await syntax over coroutines.  Thanks.

**Comment by realityking** [comment]
Hey @hunt3r, sorry it took so long to respond to this, we need to do a better job of monitoring the -labs repositories. I see from the pip output that you've tried to install contentful.py 0.9.2, please use 0.9.3 this version has support for Python 3.5.
