### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by cemsbr** [contentful-labs/contentful.py#21]
Hi, I'm a grow user and it can't be installed because of contentful (version 0.9.3):

```
$ pip install contentful.py
Collecting contentful.py
  Using cached contentful.py-0.9.3.tar.gz
Collecting enum34==1.1.1 (from contentful.py)
  Using cached enum34-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 5, in <module>
        import distutils.core
      File "/usr/lib/python3.6/distutils/core.py", line 16, in <module>
        from distutils.dist import Distribution
      File "/usr/lib/python3.6/distutils/dist.py", line 9, in <module>
        import re
      File "/usr/lib/python3.6/re.py", line 142, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ag317ju9/enum34/
```

**Comment by shaunpatterson** [comment]
https://github.com/contentful-labs/contentful.py/pull/22
